-- CreateEnum
CREATE TYPE "CAMPAIGN_PRIORITY" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- AlterTable
ALTER TABLE "campaigns" ADD COLUMN     "batch" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'NGN',
ADD COLUMN     "location" TEXT,
ADD COLUMN     "priority" "CAMPAIGN_PRIORITY" NOT NULL DEFAULT 'LOW',
ALTER COLUMN "story" DROP NOT NULL;
