name: NestJS CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test --if-present

            - name: Build project
              run: npm run build

            - name: Deploy to Render
              env:
                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
                  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
              run: |
                  curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  -H "Accept: application/json" \
                  -d ''
